
name: test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, new-random ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    container:
      image: ${{matrix.cfg.container}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        cfg:
          - { container: "rpgoldman/sbcl:latest", lisp: sbcl }
          - { container: "rpgoldman/ccl:latest", lisp: ccl }

    steps:
    - name: Get validate deps
      shell: bash
      run: |
        apt-get update
        apt-get install -y cmake make g++ flex bison

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: cache validate
      id: cache-validate
      uses: actions/cache@v3
      with:
        path: jenkins/ext/VAL
        key: ${{ runner.os }}
    - name: compile validate
      if: steps.cache-validate.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd jenkins/ext/VAL
        make

    - name: add validate to path
      run: echo "${GITHUB_WORKSPACE}/jenkins/ext/VAL" >> $GITHUB_PATH

    - name: tests
      shell: bash
      run: |
        cd jenkins
        ./run-tests.sh ${{ matrix.cfg.lisp }}
